import pandas as pd
import numpy as np
import joblib
import itertools

def generate_counterfactual(model, original_x, target_index=0):
    pred = model.predict([original_x])[0]
    if pred[target_index] == 1:
        return "N/A (Accepted)", 0.0
        
    step = 0.05
    max_steps = 10
    step_ranges = [range(max_steps + 1) for _ in range(4)]
    
    # Generate all candidate perturbations
    perturbations = np.array(list(itertools.product(*step_ranges))) * step
    
    # Filter out the zero perturbation (original_x)
    non_zero_mask = np.sum(perturbations, axis=1) > 0
    perturbations = perturbations[non_zero_mask]
    
    # Create candidate matrix
    candidates = np.clip(original_x + perturbations, 0, 1.0)
    
    # Vectorized predict
    preds = model.predict(candidates)
    
    # Filter accepted candidates
    accepted_mask = preds[:, target_index] == 1
    
    if not np.any(accepted_mask):
        return "No realistic CF", -1
        
    valid_perturbations = perturbations[accepted_mask]
    valid_candidates = candidates[accepted_mask]
    
    # Calculate distances
    distances = np.sqrt(np.sum((valid_candidates - original_x)**2, axis=1))
    
    # Find minimum distance
    best_idx = np.argmin(distances)
    best_cf = valid_perturbations[best_idx]
    min_dist = distances[best_idx]
    
    advice = f"+{best_cf[0]*100:.0f}\\% M, +{best_cf[1]*100:.0f}\\% P, +{best_cf[2]*100:.0f}\\% C, +{best_cf[3]*100:.0f}\\% B"
    return advice, min_dist

def main():
    print("Generating massive Counterfactual Appendix C table...")
    model = joblib.load('../DATA/best_cc_model.pkl')
    # Load 500 unique students for the actual dataset
    df = pd.read_csv('../DATA/processed_multilabel_data.csv').drop_duplicates().sample(500, random_state=42)
    features = ['Math_Score_Normalized', 'Physics_Score_Normalized', 'Chemistry_Score_Normalized', 'Biology_Score_Normalized']
    
    latex_out = "\\section*{Appendix C: Comprehensive Simulated Counterfactual Pathways}\\label{app:counterfactuals}\n"
    latex_out += "This appendix details the mathematical counterfactuals generated by the XGBoost Classifier Chain for a representative sample of 500 students aiming for the \\textbf{Medicine} track. It demonstrates the personalized pedagogical action plans required to flip a rejection to an acceptance based on the $L_2$ distance minimization algorithm.\\vspace{1em}\n\n"
    
    latex_out += "\\begin{longtable}{l c c c c | c | l}\n"
    latex_out += "\\caption{Generated Counterfactuals for Medicine Track Aspirants}\\\\\n"
    latex_out += "\\toprule\n"
    latex_out += "\\textbf{Student ID} & \\textbf{Math} & \\textbf{Phys} & \\textbf{Chem} & \\textbf{Bio} & \\textbf{Current Status} & \\textbf{Actionable Advice ($\\Delta$)} \\\\\n"
    latex_out += "\\midrule\n"
    latex_out += "\\endfirsthead\n\n"
    
    latex_out += "\\multicolumn{7}{c}%\n"
    latex_out += "{{\\bfseries \\tablename\\ \\thetable{} -- continued from previous page}} \\\\\n"
    latex_out += "\\toprule\n"
    latex_out += "\\textbf{Student ID} & \\textbf{Math} & \\textbf{Phys} & \\textbf{Chem} & \\textbf{Bio} & \\textbf{Current Status} & \\textbf{Actionable Advice ($\\Delta$)} \\\\\n"
    latex_out += "\\midrule\n"
    latex_out += "\\endhead\n\n"
    
    latex_out += "\\midrule \\multicolumn{7}{r}{{Continued on next page}} \\\\\n"
    latex_out += "\\endfoot\n\n"
    latex_out += "\\bottomrule\n"
    latex_out += "\\endlastfoot\n\n"
    
    rows = []
    student_id = 1000
    for i, (_, row) in enumerate(df.iterrows()):
        x = row[features].values.astype(float)
        math, phys, chem, bio = x
        pred = model.predict([x])[0]
        status = "\\textcolor{red}{Rejected}" if pred[0] == 0 else "\\textcolor{blue}{Accepted}"
        
        if pred[0] == 0:
            advice, dist = generate_counterfactual(model, x, 0)
        else:
            advice = "N/A (Accepted)"
            
        latex_out += f"STU-{student_id} & {math:.2f} & {phys:.2f} & {chem:.2f} & {bio:.2f} & {status} & {advice} \\\\\n"
        student_id += 1
        
        if i % 50 == 0:
            print(f"Processed {i}/500 students...")
            
    latex_out += "\\end{longtable}\n"
    
    with open('../THESIS/text/Appendix_C_Counterfactuals.tex', 'w') as f:
        f.write(latex_out)
        
    print("Appendix C generated successfully!")

if __name__ == "__main__":
    main()
